### ISSUE TITLE
warning : exception specification for virtual function...

### ISSUE THREAD

**Issue by LeonineKing1199** [philsquared/Catch#755] opened 2016-11-29 04:27 UTC
I'm trying to integrate Catch into my project and I keep getting these warnings:
```
"C:\Users\christian\cuda\cuda-stuff\build\regulus.sln" (default target) (1) ->
       "C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj.metaproj" (default target) (3) ->
       "C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj" (default target) (4) ->
       (CustomBuild target) ->
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::SharedImpl<T>::~SharedImpl [with T=Catch::IShared]" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::IShared::~IShared" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::NonCopyable::~NonCopyable" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::SharedImpl<T>::~SharedImpl [with T=Catch::IShared]" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::IShared::~IShared" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::NonCopyable::~NonCopyable" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::SharedImpl<T>::~SharedImpl [with T=Catch::IShared]" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::IShared::~IShared" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::NonCopyable::~NonCopyable" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::SharedImpl<T>::~SharedImpl [with T=Catch::IShared]" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::IShared::~IShared" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::NonCopyable::~NonCopyable" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::SharedImpl<T>::~SharedImpl [with T=Catch::IShared]" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::IShared::~IShared" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::NonCopyable::~NonCopyable" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::SharedImpl<T>::~SharedImpl [with T=Catch::IShared]" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::IShared::~IShared" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::NonCopyable::~NonCopyable" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
         C:\Users\christian\cuda\cuda-stuff\include\catch.hpp(908): warning : exception specification for virtual function "Catch::Matchers::Impl::Matcher<ExpressionT>::~Matcher [with ExpressionT=Exp
       ressionT]" is incompatible with that of overridden function "Catch::SharedImpl<T>::~SharedImpl [with T=Catch::IShared]" [C:\Users\christian\cuda\cuda-stuff\build\regulus.vcxproj]
```

I'm building CUDA 8 on Windows 10 with MSVS 14.0. I can post the relevant CMakeLists.txt file if required.

**Comment by lightmare** [comment] 2016-11-30 02:26
That's MSVC's broken exception-specification on destructors. All of these should be implicitly `noexcept`, as there are no throwing base- or member- dtors involved. But for some reason MSVC concludes different exception-specification for inline and out-of-line dtors. You can fix this by either adding `noexcept` to all of them, or just delete the redundant `~Matcher` override.

**Comment by LeonineKing1199** [comment] 2016-11-30 16:38
Oh, the fix is so easy and oddly mechanical O_o

Well, there's some good news for you guys, I have professional data entry experience. If I explicitly added `noexcept` to them all, should I make a formal pull request? Will I have to first test my code against gcc as well?

**Comment by horenmar** [comment] 2017-01-17 11:02
As far as I can tell this hasn't reappeared, so I am going to close it.

**Comment by LeonineKing1199** [comment] 2017-02-02 21:01
I just downloaded Catch 1.7 and the error has reappeared. I am attempting the same fix from before.

**Comment by horenmar** [comment] 2017-02-03 18:35
Is this caused by the cuda compiler or some warning level in MSVC? (Mostly asking because I can't reproduce with MSVC).

**Comment by LeonineKing1199** [comment] 2017-02-04 15:34
That's a really good question, actually. I'll check it out and be sure to report back with my findings. For MSVC, I'm just using `/W3` or rather, whatever the default compiler options for CMake's Debug build.

**Comment by philsquared** [comment] 2017-02-08 15:46
I've been reworking the Matchers implementation and they now use a lot less templates and other noise (including those destructors). It's not on master yet, mostly because it has some potential for breaking code that defines their own matchers - and I haven't had a chance to compile with high warnings yet.

But you can find them here:
https://github.com/philsquared/Catch/tree/new-matchers

(or just the single include:
https://github.com/philsquared/Catch/raw/new-matchers/single_include/catch.hpp)

I'd appreciate if you could give your case a try with this version to see if you still have the same (or some other) issue.

**Comment by horenmar** [comment] 2017-03-24 21:48
Since there has been no followup in 3 weeks, I am going to close this. If it comes back, reopen or open a new issue.

**Closed by horenmar** 2017-03-24 21:48 UTC
Labels: Resolved - pending review
