### ISSUE TITLE
Catch won't compile, throwing some incomprehensible template errors

### ISSUE THREAD

**Issue by CelticMinstrel** [philsquared/Catch#450] opened 2015-06-30 01:59 UTC
I can't compile the minimal Catch program (just the `#define CATCH_CONFIG_MAIN` and `#include "catch.hpp"`) with XCode 4.5.2 (clang 4.2 or so) on Mac OSX Lion, using the default version of libc++. The error log is rather long, but you can view it [here](http://celmin.pwcsite.com/misc/catch_build_errors.txt). I tried to go through the errors and figure out the cause, but was unable to make any progress.

I just downloaded the single-include header earlier today from here on github, so it's presumably the latest copy. Is there anything I can do to fix this issue, or could it be that my compiler/library is just too old?

**Comment by kirbyfan64** [comment] 2015-06-30 14:04
> clang 4.2 or so

The latest version is 3.6.1...

**Comment by philsquared** [comment] 2015-06-30 17:29
I don't have a copy of Xcode 4 around, still, to try this on - but from the error message you posted (thanks for that) it looks like it's the std::map keyed on the type it's a member of that's an issue.
It looks like it's only the *use* of that map (in the methods) that it's having trouble with (seems to be from my scanning of the errors). So I've separated the implementation of those methods out.

This is included in v1.2.1, so please check that out and let me know if it fixes it for you.

**Comment by CelticMinstrel** [comment] 2015-06-30 21:03
I just redownloaded from the link in the readme, and the problem still occurs. Except for line/column numbers, the error messages are identical.

There's also an error on the following code which makes no sense (it was present before as well, but I fixed it as it seemed a trivial issue unrelated to the main problem):

    inline TrackedSection* TrackedSection::findChild( std::string const& childName ) {
        TrackedSections::iterator it = m_children.find( childName );
        return it != m_children.end()
            ? &it->second
            : NULL;

Reversing the order of the logic (ie, using `==` instead of `!=` and reversing the order of the other two operands) seems to fix it, though I can't comprehend why it occurs in the first place (the actual error is below; I imagine you'll agree it doesn't make sense):

    ~/Documents/Programming/Blades Of Exile/src/../rsrc/../test/catch.hpp:4978:20: error: expected ':'
                ? &it->second
                       ^
    ~/Documents/Programming/Blades Of Exile/src/../rsrc/../test/catch.hpp:4978:13: note: to match this '?'
                ? &it->second
                ^
    ~/Documents/Programming/Blades Of Exile/src/../rsrc/../test/catch.hpp:4978:20: error: use of undeclared identifier 'second'
                ? &it->second

@kirbyfan64 - Well, `clang --version` returns `Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)`. Maybe I just parsed out the wrong portion of that for the version.

**Comment by philsquared** [comment] 2015-06-30 22:09
That's a shame.
I think the other error you are seeing (with the `?:` operator) is a consequence of the first (because the type of `second` is incomplete it can't match it against NULL)

**Comment by philsquared** [comment] 2015-06-30 22:10
actually that can't be the case as TrackedSection is no longer incomplete at that point. Hmmm

**Comment by kirbyfan64** [comment] 2015-06-30 22:19
@CelticMinstrel What about trying a newer version of Clang? I know that 3.2 was a bit buggier than later releases and had given be trouble a few times.

Whatever the issue is, it's definitely not present in newer versions: I use Clang 3.6 and have never encountered this issue.

**Comment by CelticMinstrel** [comment] 2015-06-30 22:36
If I use a newer version of clang it doesn't work correctly with XCode due to APIs changing or something. Or at least, that was the case the last time I tried (which admittedly was a few years ago, and I think there was an XCode update since then, so it might be worth trying again; just have to remember how). Keep in mind though that my XCode is also old, and I can't update it because the newer versions don't support my system.

**Comment by philsquared** [comment] 2015-07-01 17:21
Thanks. I'll close this issue as it is resolved for you. I might still try and avoid the self-referential nature of TrackedSection, though.
Thanks for bringing it up.

**Closed by philsquared** 2015-07-01 17:21 UTC

**Comment by vadz** [comment] 2015-09-07 14:27
FWIW I just ran into the same problem with CATCH 1.2.1 while compiling something using 10.8 SDK (for compatibility with OS X 10.7). This does look like a bug in compiler (mine is even older, it's `Apple clang version 4.1 (tags/Apple/clang-421.11.66) (based on LLVM 3.1svn)`), but I'm not completely sure.

Notice that this only happens if `-std=c++11` is used, without it everything is fine (whether using `-stdlib=libc++` or not).
