### ISSUE TITLE
JUnit reporter skips writing results of some tests

### ISSUE THREAD

**Issue by PeterSchuebel** [philsquared/Catch#1025] opened 2017-09-18 15:08 UTC
## Description
Since upgrading from v1.9.4 to v1.10.0 we noticed that the JUnit reporter produces much smaller XML files.
A closer investigation showed that all the tests are still run (total runtime was roughly the same and number of tests was identical), but much fewer tests get reported in the output file. So we think it's an issue in the JUnit reporter, rather than in Catch itself.
Apart from upgrading Catch last Tuesday, nothing else had changed in our Test code or build system, so we think it is a recently introduced issue in Catch.

### Steps to reproduce
Further investigation showed:
* this affects TESTs that use SECTIONs and those that don't (shown as 'global' in output), so it's not related to previous bugs with the JUnit reporter
* TESTs that don't get reported only used REQUIRE and CHECK macros.
* adding the usage of a CHECK_THROWS(<expression>) macro to a TEST that was not reported caused it to get reported.

A workaround I found is to add the '--success' parameter to the command line.  Then all tests get reported. We use this now in our CI server, but for every day command line usage it would be nice to have this looked at and fixed.

### Extra information

We use the following code to include Catch:

#define CATCH_CONFIG_CPP11_NULLPTR
#define CATCH_CONFIG_CPP11_IS_ENUM
#define CATCH_CONFIG_CPP11_TUPLE
#define CATCH_CONFIG_CPP11_LONG_LONG
#define CATCH_CONFIG_CPP11_OVERRIDE
#define CATCH_CONFIG_CPP11_UNIQUE_PTR
#define CATCH_CONFIG_CPP11_TYPE_TRAITS
#define CATCH_CONFIG_CPP11_OR_GREATER
#define CATCH_CONFIG_VARIADIC_MACROS
#define CATCH_CONFIG_WINDOWS_SEH
#define CATCH_CONFIG_COUNTER

#define CLARA_CONFIG_CPP11_NULLPTR
#define CLARA_CONFIG_CPP11_OVERRIDE
#define CLARA_CONFIG_CPP11_UNIQUE_PTR
#define CLARA_CONFIG_CPP11_OR_GREATER

#pragma warning (push)
#pragma warning (disable:4702) // unreachable code when trowing exceptions inside Catch macros, e.g. REQUIRE_THROWS_AS
#include "catch.hpp"
#pragma warning (pop)

* Catch version: **v1.10.0**
* Operating System: **Windows 10**
* Compiler+version: **MSVC 2013 Update 4**

**Comment by Gus-Corvil** [comment] 2017-09-18 15:39
Same for me here on Ubuntu 16.04.3 LTS.
Not using any of those fancy #defines here, we just upgraded from v1.5.6.
Issue must have appeared on v1.9.7, since v1.9.6 is the highest working fine for me.

**Comment by philsquared** [comment] 2017-09-18 16:52
Looks like a change went in on 7th July that stops successful assertions being passed to the reporter if you haven't specified `--success`/`-s`. I believe this was done in the name of performance - probably not realising that the decision whether to report successful results rests with the reporter (and thus changing behaviour).

Now, as it happens I think that it's the right thing to do, anyway (filter successful results before they get to the reporter, if `-s` is not specified). It puts the user in control (and potentially simplifies some internal code). [I was even talking about this five years ago](https://github.com/philsquared/Catch/issues/128) (although, now I read back, it looks like I was excluding the JUnit reporter due to "convention").

However I don't think that change should have gone into a patch release (even if we're doing off-by-one semver). But it's there now so I think we'll need to run with it.

So, if we interpret all the above as, "working as designed" (setting aside the slightly accidental design process), do you still have an objection to supplying `-s`?

@PeterSchuebel you say you're ok with it on the CI server, but you'd like it changed for "everyday command line use". Are you using the JUnit reporter locally from the command line? I would expect you'd be using the console reporter (or perhaps compact) - or some IDE integration? If so then the non-reporting of successful assertions has always been the default. Perhaps you could clarify?

**Comment by PeterSchuebel** [comment] 2017-09-18 17:02
Thanks for the explanation, Phil.
It still seems somewhat inconsistent. Why are 15 out of 73 successful TESTs being reported then? I think it should be 0 according to your explanation. Are tests related to exceptions (e.g. thrown, but expected ; or expected to not throw) treated differently? And if so, why?

Yes, we're fine for now to go with '-s'.
We mostly use the Console reporter from the command line. It's just sometimes useful to compare detailed outputs when making code change, to see the effect, e.g. using a merge tool on the before/after XML files.
Not a big deal, and you're right that it actually is more consistent with what the Console reporter already does. Now that we know, it's OK to adapt and continue with this JUnit behaviour.

**Comment by philsquared** [comment] 2017-09-18 17:08
> Why are 15 out of 73 successful TESTs being reported then?

Hmm, that sounds like something different.
The change I mentioned was that successful assertions are not passed on to the reporter. The test cases (and sections) they are in are, though. So when you say, "15 out of 73 successful TESTS" do you mean assertions (`CHECK`, `REQUIRE` etc) or `TEST_CASE`s?

It sounds like you mean `TEST_CASE`s - in which case what I said before is not the explanation (although it may still be related).
I couldn't see evidence of what you're seeing in our our self-test runs (we capture the output as baselines and diff them as a form of regression) - but there were some test cases that stopped being reported for what I thought were different reasons. I'll have to go and look at those in more detail. So I'm going to re-open this ticket for now as I think we may still have an issue here.
If you're able to provide any more information - or come up with a minimum example that you can share that shows the problem (to save us talking any more cross purposes) that would be great!

**Comment by PeterSchuebel** [comment] 2017-09-18 17:43
I meant 15 out of 73 TEST_CASES or SECTIONS.

```
TEST_CASE("JUnit reporter", "[JUnit]")
{
    SECTION("CHECK 1 NotReported")
    {
        CHECK(1 == 1);
        SECTION("CHECK 1a NotReported")
        {
            CHECK(1 == 1);
        }
        SECTION("CHECK 1b NotReported")
        {
            CHECK(1 == 1);
        }
    }
    SECTION("CHECK NotReported")
    {
        CHECK(1 == 1);
    }
    SECTION("SUCCEED Reported")
    {
        SUCCEED("OK");
    }
    SECTION("FAIL Reported")
    {
        FAIL("FAIL");
    }
    SECTION("CHECK_THROWS Reported")
    {
        CHECK_THROWS(throw std::exception());
    }
    SECTION("CHECK_NOTHROW Reported")
    {
        int dummy;
        CHECK_NOTHROW((void*)dummy);
    }
}
```
Produces:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="d3_test.exe d3core_test.dll" errors="0" failures="1" tests="9" hostname="tbd" time="0.000326" timestamp="2017-09-18T17:37:13Z">
    <testcase classname="JUnit reporter" name="SUCCEED Reported" time="0.000005"/>
    <testcase classname="JUnit reporter" name="FAIL Reported" time="0.00009">
      <failure type="FAIL">
FAIL
at test_citp.cpp(75)
      </failure>
    </testcase>
    <testcase classname="JUnit reporter" name="CHECK_THROWS Reported" time="0.00002"/>
    <testcase classname="JUnit reporter" name="CHECK_NOTHROW Reported" time="0.000001"/>
    <system-out/>
    <system-err/>
  </testsuite>
</testsuites>
```

**Comment by PeterSchuebel** [comment] 2017-09-18 17:45
If I use the -s switch, then the SECTIONs marked "NotReported" turn up in the output.

**Comment by Gus-Corvil** [comment] 2017-09-19 10:16
Actually the `--success` command line switch seems to make the problem disappear with no apparent side effect in the junit XML output.

**Comment by philsquared** [comment] 2017-09-19 12:56
Thanks for the example, @PeterSchuebel.
That allowed me to nail out down quite quickly.
I can see now that, when the change was applied in July, it was only on one of the paths that led to the assertion being reported. So for some types of assertion the reporting was completely suppressed (leading to 0 assertions in a `SECTION`, which caused the JUnit reporter to not report the section at all) - and others it was only suppressed within the JUnit reporter itself (so it printed the `SECTION`, but then skipped the assertions).

Fixing this would not be a huge job, but it would be a bit fiddlier than I'd like to commit to in Catch 1.x - especially since all the impacted logic has changed in Catch2 and (I just checked) it does not have this issue!

So, since it's just a weird inconsistency, but not inaccuracy, I'm going to propose leaving this, after all.
I'd encourage you to try out Catch2, though (currently on a branch, but I'll be promoting it to master in the near future). Assuming you have a C++11 capable compiler?

**Comment by PeterSchuebel** [comment] 2017-09-19 13:29
We use MSVC 2013u4, so yes, C++11 capable. We are in the process of moving to MSVC 2017. So we probably move to Catch2 just before that; but we will wait for the move to master.

From my side it's OK to close the ticket. Thank you very much for Catch!

**Comment by philsquared** [comment] 2017-09-19 13:35
Thanks. I'll re-close.
I forget what now, but I have a feeling VS2013 may not be enough (although it's possible whatever the issue was got fixed in a later update - not rechecked for a while).

**Closed by philsquared** 2017-09-19 13:35 UTC
