### ISSUE TITLE
PVS Studio Analyzer 

### ISSUE THREAD

**Issue by drillsar** [philsquared/Catch#951] opened 2017-07-09 15:48 UTC
I ran the PVS Studio analyzer Log

V730 catch_reporter_junit.hpp 52 Not all members of a class are initialized inside the constructor. Consider inspecting: unexpectedExceptions.

V667 catch_interfaces_exception.h 46 The 'throw' operator does not possess any arguments and is not situated within the 'catch' block.

V667 catch.hpp 2720 The 'throw' operator does not possess any arguments and is not situated within the 'catch' block.

Catch version 1.9.3

**Comment by horenmar** [comment] 2017-07-10 08:22
The third one I assume is from the single-include header, so it is a duplicate of second one.

Anyway, second one is bogus, it is hidden away in a function, but that function is called from inside a catch block, so the `throw;` just rethrows currently handled exception.

The first one is harmless as well, but there is no harm in silencing the warning by initializing it in the constructor as well.

**Closed** 2017-07-10 08:30 UTC
