### ISSUE TITLE
Never-ending loop wjhen the test case Failed

### ISSUE THREAD

**Issue by dsamek** [philsquared/Catch#271] opened 2014-04-15 05:51 UTC
If I use this piece of code:

```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

#include "TCACAVAUtilities.h"

TEST_CASE( "TCACAVAUtilities::CreateColorFromRGB", "[CreateColorFromRGB]" ) {
    REQUIRE( TCACAVAUtilities::CreateColorFromRGB(0, 0, 0) == 255 );
}
```

The result is:

```
C:\SourceCode\CVS_ROOT\CAVA\develop_clean\win_b64\code\bin>TCACAVACreateBaseCatalog.exe
All tests passed (1 assertion in 1 test case)
```

But If I use this code:

```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

#include "TCACAVAUtilities.h"

TEST_CASE( "TCACAVAUtilities::CreateColorFromRGB", "[CreateColorFromRGB]" ) {
    REQUIRE( TCACAVAUtilities::CreateColorFromRGB(1, 0, 0) == 255 );
    REQUIRE( TCACAVAUtilities::CreateColorFromRGB(0, 0, 0) == 255 );
}
```

The result is:

```
-------------------------------------------------------------------------------
TCACAVAUtilities::CreateColorFromRGB
-------------------------------------------------------------------------------
C:\SourceCode\CVS_ROOT\CAVA\develop_clean\TCACAVACatalog\TCACAVACreateBaseCatalo
g.m\src\TCACAVACreateBaseCatalog.cpp(6)
...............................................................................

C:\SourceCode\CVS_ROOT\CAVA\develop_clean\TCACAVACatalog\TCACAVACreateBaseCatalo
g.m\src\TCACAVACreateBaseCatalog.cpp(7): FAILED:
  REQUIRE( TCACAVAUtilities::CreateColorFromRGB(1, 0, 0) == 255 )
with expansion:
  0x10000ff == 255

-------------------------------------------------------------------------------
TCACAVAUtilities::CreateColorFromRGB
-------------------------------------------------------------------------------
C:\SourceCode\CVS_ROOT\CAVA\develop_clean\TCACAVACatalog\TCACAVACreateBaseCatalo
g.m\src\TCACAVACreateBaseCatalog.cpp(6)
...............................................................................

C:\SourceCode\CVS_ROOT\CAVA\develop_clean\TCACAVACatalog\TCACAVACreateBaseCatalo
g.m\src\TCACAVACreateBaseCatalog.cpp(7): FAILED:
  REQUIRE( TCACAVAUtilities::CreateColorFromRGB(1, 0, 0) == 255 )
with expansion:
  0x10000ff == 255

-------------------------------------------------------------------------------
TCACAVAUtilities::CreateColorFromRGB
-------------------------------------------------------------------------------
C:\SourceCode\CVS_ROOT\CAVA\develop_clean\TCACAVACatalog\TCACAVACreateBaseCatalo
g.m\src\TCACAVACreateBaseCatalog.cpp(6)
...............................................................................

C:\SourceCode\CVS_ROOT\CAVA\develop_clean\TCACAVACatalog\TCACAVACreateBaseCatalo
g.m\src\TCACAVACreateBaseCatalog.cpp(7): FAILED:
  REQUIRE( TCACAVAUtilities::CreateColorFromRGB(1, 0, 0) == 255 )
with expansion:
  0x10000ff == 255

-------------------------------------------------------------------------------
TCACAVAUtilities::CreateColorFromRGB
-------------------------------------------------------------------------------
C:\SourceCode\CVS_ROOT\CAVA\develop_clean\TCACAVACatalog\TCACAVACreateBaseCatalo
g.m\src\TCACAVACreateBaseCatalog.cpp(6)
...............................................................................

C:\SourceCode\CVS_ROOT\CAVA\develop_clean\TCACAVACatalog\TCACAVACreateBaseCatalo
g.m\src\TCACAVACreateBaseCatalog.cpp(7): FAILED:
  REQUIRE( TCACAVAUtilities::CreateColorFromRGB(1, 0, 0) == 255 )
with expansion:
  0x10000ff == 255

-------------------------------------------------------------------------------
TCACAVAUtilities::CreateColorFromRGB
-------------------------------------------------------------------------------
C:\SourceCode\CVS_ROOT\CAVA\develop_clean\TCACAVACatalog\TCACAVACreateBaseCatalo
g.m\src\TCACforrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source

libifcoremd.dll    00000000100BAB14  Unknown               Unknown  Unknown
libifcoremd.dll    00000000100B46B9  Unknown               Unknown  Unknown
libifcoremd.dll    00000000100A1017  Unknown               Unknown  Unknown
libifcoremd.dll    0000000010021BF8  Unknown               Unknown  Unknown
libifcoremd.dll    000000001002DDC8  Unknown               Unknown  Unknown
kernel32.dll       00000000774F4803  Unknown               Unknown  Unknown
kernel32.dll       00000000774B652D  Unknown               Unknown  Unknown
ntdll.dll          00000000776EC541  Unknown               Unknown  Unknown
```

The never-ending loop which should I stop with CTRL+C.

Where is the problem ? Do I something wrong ?

**Comment by joto** [comment] 2015-01-16 19:12
The commit doesn't fix the issue for me.

**Comment by AlexisWilke** [comment] 2015-04-05 01:33
I just ran into this problem with library zipios++. The test works fine under Linux which uses g++ but fails and loops forever under FreeBSD with clang. I would imagine that the difference in compiler is the culprit here, but what do I know?!

If you'd like more precision about the test I have that fails, let me know.

"use Zipios++ to create zip archives with 1 or 3 files each"

The code is in this file:

https://sourceforge.net/p/zipios/git-code/ci/master/tree/tests/catch_zipfile.cpp

**Comment by AlexisWilke** [comment] 2015-04-05 06:12
After reading the entire thread and testing with Joto suggestion, I found out that I am indeed getting the same problem: std::uncaught_exception(). I'm thinking that this flag is set to true when it should not be, unless I missed something somewhere -- i.e. a throw in a destructor. So I search for such without luck thus far. However, I definitively have an exception which is caught as expected by the REQUIRE_THROWS_AS() macro.

The only particularity of that specific test is that it calls a function that rethrows an exception, although I tried to throw a new exception instead of just using `throw` it did not help. I think that somehow clang does not want to reset the std::uncaught_exception() flag and I'm not too sure there is anything we can do about it except adding a hack to catch.hpp if compiled by clang.

**Comment by philsquared** [comment] 2015-04-09 17:37
Thanks for the additional info, @AlexisWilke. Interesting that it seems to be a clang thing as I use clang  on Mac OS X and have never seen the issue. I can't see why something like this would be platform dependent - but the Mac version is Apple's own fork, so it could be that.
I need to look into this more, again. I'm not against putting in a conditional workaround for clang, if we can find one general enough.
I'm not really getting any time to look at Catch at the moment, as I have a couple of big things going on. I'm hoping to be back on it in a couple of weeks.

**Comment by AlexisWilke** [comment] 2015-04-09 18:57
It could be that the clang people have a fix which did not make it in the version used by FreeBSD. I'm just using the latest FreeBSD in a virtual host (10.1). If you'd like to test with my test case, you can get zipios++ from the git repository on SourceForge.net and then compile it. You may put catch.hpp in the contrib/... directory so the tests get compiled. You may remove the #ifndef __clang__ although running all the tests in one go generate the problem too. I now have a script that runs the tests one by one and except for the few that are "protected" with the #ifndef, all the other tests pass. Obviously that means I don't cover as much code, but I still think zipios is very well tested under FreeBSD too at the moment.

**Comment by joto** [comment] 2015-04-09 22:19
I have the problem whether I compile with clang or with gcc, so I don't think it is a compiler bug. (Tested on Debian Jessie.)

**Comment by AlexisWilke** [comment] 2015-04-13 00:07
Joto, just in case I tested my code under Debian (Wheezy and Jessie) and it worked just fine. Are you using the latest version of catch.hpp? phil made some fixes at some point which may not have been updated?

**Comment by kirbyfan64** [comment] 2015-04-13 00:54
Considering the fact that this can be so hard to reproduce, this might be a C++ stdlib/ABI bug. Can someone who has the bug try this with libc++ or libcxxabi?

**Comment by joto** [comment] 2015-04-13 08:53
@AlexisWilke just tried CATCH v1.1 build 14 and it still hangs with GCC 4.9.2 and Clang 3.5.0.

**Comment by AlexisWilke** [comment] 2015-04-13 20:26
I tried now with g++ 4.9.1. I suppose the latest libstd++ (or at least the one in 4.9.2) is different enough to were you would get that problem. Either that, or my code does not expose the problem in g++.

How could I test with the latest under Ubuntu? Any easy apt-get install stuff that would help? Actually, I will look for version 15.04. Maybe it has a version that breaks.

**Comment by joto** [comment] 2015-04-14 07:39
Okay, I have boiled down the case I have been having trouble with to a few simple test cases. Here is the code:

```
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include <future>
#include <stdexcept>

TEST_CASE("value") {
    SECTION("works") {
        std::promise<int> result;
        result.set_value(42);
        REQUIRE(result.get_future().get() == 42);
    }
}

TEST_CASE("exception") {
    SECTION("throws") {
        std::promise<int> result;
        try {
            throw std::runtime_error("Example");
        } catch(...) {
            result.set_exception(std::current_exception());
        }
        REQUIRE(result.get_future().get() == 42);
    }
}

TEST_CASE("require") {
    SECTION("hangs") {
        std::promise<int> result;
        try {
            throw std::runtime_error("Example");
        } catch(...) {
            result.set_exception(std::current_exception());
        }
        REQUIRE_THROWS_AS(result.get_future().get(), std::runtime_error);
    }
}
```
Save as `catch_hang.cpp` and compile: `g++ -std=c++11 catch_hang.cpp -o catch_hang -pthread`. Use the compiler of your choice, `g++` and `clang++` show the same behaviour for me.

Now run these commands in turn:
```
./catch_hang value        # works as it should
./catch_hang exception # shows that an exception is thrown from the get()
./catch_hang require     # problem case
```

The last case hangs forever with `CATCH v1.0 build 53`. With `CATCH v1.1 build 14` it also hangs, but when I hit CTRL-C to break it off, it prints 'require' forever and I have to hit CTRL-C again to stop it.

[cppreference.com](http://en.cppreference.com/w/cpp/error/uncaught_exception) tells me that `uncaught_exception()` "Detects if the current thread has a live exception object", so maybe it doesn't detect the exception "hidden" in the promise?

**Comment by kirbyfan64** [comment] 2015-04-14 15:58
I get a slightly different result:

```
$ ./catch_hang require
# hangs here
^C
require
require
require
require
require
require
require
require
require
require
require
require
require
require
require
require
require
require
require
require
require
...
^Crequire
^Crequire
...
  require
  require
  hangs
-------------------------------------------------------------------------------
loop.cpp:26
...............................................................................

loop.cpp:27: FAILED:
due to a fatal error condition:
  SIGINT - Terminal interrupt signal

===============================================================================
test cases:     1 |     0 passed | 1 failed
assertions: 68313 | 68312 passed | 1 failed

ryan@DevPC-LX:~/langtest/catch$ ^C
```

The `^C` are the times when I pressed `control-C` to kill the program.

**Comment by kirbyfan64** [comment] 2015-04-14 16:42
**This is a bug in libstdc++**. Compiling the program with `-stdlib=libc++` works correctly.

Looking into filing a bug report...

**Comment by kirbyfan64** [comment] 2015-04-14 16:43
Crap, I can't file one because "user account creation has been restricted."

Could someone else look into that?

**Comment by philsquared** [comment] 2015-09-27 10:30
For anyone still watching this issue - I've committed some changes (on Develop) that may address it. Please let me know either way if you try it.

**Comment by joto** [comment] 2015-09-27 18:10
@philsquared This fixes it for me! Thanks.

**Comment by philsquared** [comment] 2015-09-29 18:34
Thanks for letting me know, @joto.
Anyone else?

**Comment by gahr** [comment] 2015-10-02 17:59
@philsquared Latest master fixes it, with FreeBSD clang version 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512.

Thanks!

**Comment by philsquared** [comment] 2017-01-12 09:26
Doing some clean-up. I know it's been a while, so I don't know if the original posters are still watching, or interested - but it would be nice to be able to close this.
@dsamek, @kirbyfan64, @AlexisWilke, @matalangilbert (sorry if this is a blast from the past)?

**Comment by AlexisWilke** [comment] 2017-01-13 00:12
From what I recall, it works for me now.

**Closed** 2017-02-06 09:46 UTC
Labels: Resolved - pending review
