### ISSUE TITLE
Stack corruption or incompatibility with GDB

### ISSUE THREAD

**Issue by timoalho** [philsquared/Catch#661] opened 2016-05-16 20:02 UTC
The following code will produce inconsistent values or a sigsev when inspecting with GDB:

```
 #define CATCH_CONFIG_MAIN
 #include <catch.hpp>

 #include <stdio.h>

 SCENARIO("A sigsev occurs", "[CatchProblem]") {

    //Comment out this and the closing brace to make the problem disappear
    GIVEN("The right circumstances") {

        unsigned int number = 2;

        printf("This number should be 2: %u\n", number); //Not needed to reproduce, but will print the right number

        //Alternatively, removing the WHEN block makes the problem disappear
        WHEN("There is a when-block included") {

        }

    }

 }
```

To reproduce: compile the code and start it under the GDB debugger. Run to the line `unsigned int number = 2;`, and step over. GDB will report `Program received signal SIGSEGV, Segmentation fault.
____C_A_T_C_H____T_E_S_T____14 () at ..\src\UnitTests.cpp:18
18          unsigned int number = 2;`

Commenting out either the WHEN or GIVEN blocks makes the problem disappear.

If I add more variables the sigsev occasionally goes away, but the values of the variables in the debugger become corrupted.

My guess is that this is some form of stack corruption, although the fact that the printf will output the right number makes it plausible that there is something funny happening with GDB here instead.

Running Dr. Memory with the default settings on the test case shows no errors, although I'm not experienced enough with Dr. Memory to know how much to read into that.

Environment:
- OS: Windows 7
- GCC from mingw-w64/x86-64
- GCC 5.3.0.
- GDB 7.10.1
- Debugger running under Eclipse 4.5.1

**Comment by kirbyfan64** [comment] 2016-05-17 00:15
What happens if you run `valgrind` on it?

**Comment by timoalho** [comment] 2016-05-17 09:20
Good question. However, I'm on Windows, and last I checked valgrind is available only for Linux?

**Comment by timoalho** [comment] 2016-05-17 19:22
@kirbyfan64 I ran Dr. Memory, know errors displayed there.

**Comment by kirbyfan64** [comment] 2016-05-17 20:08
This may be a gdb bug. Just tried on Linux with both GCC and Clang, and it works perfectly.

**Comment by timoalho** [comment] 2016-05-18 10:27
@kirbyfan64 ok, thanks for trying it out. I guess I could/should submit the bug to either GDB or mingw64 then, but it might take some work to turn this into a MWE for them.

**Comment by timoalho** [comment] 2016-05-18 10:41
@kirbyfan64 just to clarify: you tried running this under GDB, running to the line with the unsigned int, and single stepping over it? Because it also works for me if I just run the program, it's the debugger that gives the error.

**Comment by kirbyfan64** [comment] 2016-05-18 13:15
@timoalho I did:

```
(gdb) break t.cpp:11 # the "unsigned int" line
(gdb) run
(gdb) s # continued single-stepping until I got sick of it...
```

**Comment by horenmar** [comment] 2017-03-08 09:25
I can't reproduce the issue on my own and there has been ton of changes in the meantime.

Unless someone can reproduce it, I am going to close this issue soon.

**Comment by horenmar** [comment] 2017-06-07 20:52
Since it has been ~3 months without new information, I am going to close this issue. If someone manages to reliably reproduce this with latest Catch, please open a new issue and link this one.

**Closed by horenmar** 2017-06-07 20:52 UTC
Labels: Can't reproduce, Resolved - pending review
