### ISSUE TITLE
Bug with std::rethrow_exception() inside SECTION()

### ISSUE THREAD

**Issue by danijar** [philsquared/Catch#460] opened 2015-07-07 11:12 UTC
Here is a minimal example illustrating the issue. It can be compiled with `g++ main.cpp --std=c++11`. Catch release 1.2.1.

```cpp
#include <exception>
#include <stdexcept>
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

void rethrow()
{
    std::exception_ptr exception;
    try {
        throw std::exception();
    } catch (...) {
        exception = std::current_exception();
    }
    std::rethrow_exception(exception);
}

TEST_CASE("in-section") {
    SECTION("exceptions can be rethrown") {
        REQUIRE_THROWS_AS(rethrow(), std::exception);
    }
}

TEST_CASE("in-setup") {
    REQUIRE_THROWS_AS(rethrow(), std::exception);
}
```

Inside the setup area, the assertion works just fine.

    $ ./a.out in-setup
    ===============================================================================
    All tests passed (1 assertion in 1 test case)

Inside SECTION() however, it clutters the console by printing the test case name forever.

    $ ./a.out in-section

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    a.out is a Catch v1.2.1 host application.
    Run with -? for options

    -------------------------------------------------------------------------------
    in-section
      in-section
      in-section
      in-section
      (... a lot of those lines)
      in-section
      exceptions can be rethrown
    -------------------------------------------------------------------------------
    main.cpp:17
    ...............................................................................

    main.cpp:18: FAILED:
    due to a fatal error condition:
      SIGINT - Terminal interrupt signal

    ===============================================================================
    test cases:      1 |      0 passed | 1 failed
    assertions: 437800 | 437799 passed | 1 failed

**Comment by kirbyfan64** [comment] 2015-07-07 14:36
I think this is a duplicate of #251 and #352...

**Comment by danijar** [comment] 2015-07-07 15:46
@kirbyfan64 Thank you very much, [this workaround][1] helps. Are there any plans on fixing this issue?

[1]: https://github.com/philsquared/Catch/issues/352#issuecomment-62646748

**Closed** 2015-07-09 11:55 UTC
