### ISSUE TITLE
constexpr expansion vs2015

### ISSUE THREAD

**Issue by Hedanito** [philsquared/Catch#449] opened 2015-06-24 18:10 UTC
I have the following constexpr values defined:

```
template <typename T> struct AngleRatios
{
    static constexpr T Radians = T(1);
    static constexpr T Degrees = MathValues<T>::Pi2 / T(360);
    static constexpr T Gradians = MathValues<T>::Pi2 / T(400);
};
```

The following check will fail saying that AngleRatios<float32>::Radians equals 0.0f

```
CHECK(AngleRatios<float32>::Radians == Approx(1.0f));
```

It will however be correct when I place braces around the expression like so:

```
CHECK( (AngleRatios<float32>::Radians == Approx(1.0f)) );
```

This will log 0.0f

```
INFO(AngleRatios<float32>::Radians)
```

This will log the correct value

```
INFO(1.0f * AngleRatios<float32>::Radians)
```

It only seems to happen with floating point values, integers expand to the correct values
Tested with Visual Studio 2015 RC.

Here is a minimal example of the bug:

```
#define CATCH_CONFIG_MAIN
#include <catch.hpp>

template <typename T> struct AngleRatios
{
    static constexpr T Radians = T(1);
};

TEST_CASE("constexpr")
{
    INFO(AngleRatios<float>::Radians);
    INFO(AngleRatios<float>::Radians * 1.0f);

    CHECK(AngleRatios<float>::Radians == Approx(1.0f));
    CHECK((AngleRatios<float>::Radians == Approx(1.0f)));
}
```

**Comment by kirbyfan64** [comment] 2015-06-24 19:02
What happens if you print the items via `std::cout`? IMO, sounds like a VS bug to me.

**Comment by PureAbstract** [comment] 2015-06-24 19:37
@Hedanito Can you post a *minimal* complete example exhibiting the problem? 

I can't reproduce here (with clang), but you don't post complete source so I can't be sure that I'm trying what you're trying. At this point, I tend to agree with @kirbyfan64 ; from the information you provide, it smells like a VS problem.

**Comment by Hedanito** [comment] 2015-06-25 19:15
Minimal example added to the original post

**Comment by kirbyfan64** [comment] 2015-06-25 19:22
Also try:

```c++
std::cout << AngleRatios<float>::Radians << std::endl;
```

If it still prints 0, it's definitely a VS bug. Try reporting it [here](https://connect.microsoft.com/VisualStudio).

**Comment by Hedanito** [comment] 2015-06-25 19:27
Printing it to `std::cout` prints `1` as expected.
It seems to work everywhere just fine, until it gets expanded by the `CHECK` macro.

**Comment by PureAbstract** [comment] 2015-06-26 16:25
I can't repro this with Clang, and don't have a machine with VS on it, so I'm guessing in the dark here, but here's a couple of other things you can try:
* Provide a definition for `Radians` as well as the declaration; I'd be surprised if that actually makes a difference in this instance, but it's worth a shot.
* Try writing the check as `CHECK( (AngleRatios<float32>::Radians) == Approx(1.0f));` - I don't honestly expect it to make any difference, but anything's possible

It still looks like a VS bug to me.

**Comment by Trass3r** [comment] 2015-08-31 07:26
webcompiler.cloudapp.net/

**Comment by kirbyfan64** [comment] 2015-08-31 14:09
@Trass3r Down for maintainance. :(

**Comment by Trass3r** [comment] 2015-10-23 07:39
@kirbyfan64 It's back :)

**Comment by horenmar** [comment] 2017-01-20 23:53
I am on VS 2015 Update 3 and the minimal example no longer triggers the problem. Given this, I am inclined to close this, unless someone still has this problem on a non-RC compiler.

**Comment by lightmare** [comment] 2017-01-21 03:32
Actually the minimal example should still trigger the issue. At least on gcc-6 it does.

It's a link error, to be clear, and here's why.
```c++
INFO(AngleRatios<float>::Radians);
CHECK(AngleRatios<float>::Radians == Approx(1.0f));
```
Expression decomposition takes a reference to both sides of the `==`. INFO also takes a reference. But there's no definition of `AngleRatios<T>::Radians`, so linking will fail.

If you use the constexpr static member in a larger constant expression, that's fine, because the compiler knows the value from the constexpr declaration, it will evaluate that expression in compile time and synthesize an unnamed variable with internal linkage to hold the result of that expression. For example this links without problem:
```c++
INFO(AngleRatios<float>::Radians * 1.0f);
```

Now, my opinion is that this is a non-issue. It can only surprise you once. Or so I thought. But it keeps recurring. There's been one with the likes of:
```c++
CHECK(std::is_pod<T>::value == true);
```
This is so easy to fix in user code, whether you construct a temporary, or add a null.
Although this never needed solving in Catch, expression decomposition got operator overloads capturing `bool` by value, not reference. That "fixes" it for `bool` only. Perhaps it'd make sense to capture all numeric types by value, but then again Catch being backward-esque, who would've wanted to write that out without the help of `<type_traits>`?

**Comment by horenmar** [comment] 2017-01-21 11:21
@lightmare If I C+P the minimal example into updated VS2015, it compiles, links and reports proper results.

According to my understanding of the original issue, RC VS2015 compiled, linked and reported wrong results.


After checking on linux, neither gcc nor clang can actually link this, so I am probably going to open up an overarching issue about that, but still close this one. If you can find the other similar issue, I am going to link both.

**Comment by horenmar** [comment] 2017-03-24 21:45
I am going to tag this with a revisit* label and close it for now, as the original issue was resolved.

* At some point Ill have to go back and decide what to do about the Clang and GCC linker error.

**Closed by horenmar** 2017-03-24 21:45 UTC
Labels: Resolved - pending review
