### ISSUE TITLE
REQUIRE don't support complex expressions

### ISSUE THREAD

**Issue by ayende** [philsquared/Catch#787] opened 2017-01-20 20:53 UTC
I have code like this:

```
std::pair<bool, long> read = t.try_read("foo");
REQUIRE(read.first && read.second == 1);
```

But `REQUIRE` doesn't wrap the passed expression in parenthesis, so it fails to compile.

**Comment by kirbyfan64** [comment] 2017-01-20 21:30
You can just do:

```c++
REQUIRE(read.first);
REQUIRE(read.second == 1);
```

If the first fails, the second won't run anyway.

ref. #341

**Comment by horenmar** [comment] 2017-01-20 23:34
While its not obvious at first, its by design to keep the underlying expression template machinery to minimum (also some more philosophical reasons). I'd recommend either a Matcher, or wrapping the expression in parentheses yourself.

**Comment by lightmare** [comment] 2017-01-21 03:46
@ayende In this particular case, by not compiling this Catch is doing you a favor ) If you rewrite that as kirbyfan suggests, and the `try_read` fails one day, you'll know whether `read.first` was false, or `read.second` had the wrong value. You wouldn't be able to learn that from the single check that lumps them together.

**Comment by horenmar** [comment] 2017-01-30 18:45
I improved the documentation regarding asserts and now I am going to close this (actually I hoped github would autoclose this issue, but apparently the detection does not support list of commits :smile:).

**Closed by horenmar** 2017-01-30 18:45 UTC
Labels: Working as intended
