### ISSUE TITLE
--name should be used in junit name="<--name>" attribute

### ISSUE THREAD

**Issue by SebastianTroy** [philsquared/Catch#638] opened 2016-04-08 14:45 UTC
Currently all junit files generated by Catch set the name attribute of the `<testsuite>` tag to "all tests", this is causing issues with my JUnit test reporter where it requires unique names to report all of the files together (it currently overwrites any testsuite with the same name meaning I can only report a single file.

**Comment by nabijaczleweli** [comment] 2016-04-10 18:11
Can you provide a testcase for that?

**Comment by SebastianTroy** [comment] 2016-04-11 11:40
I'm not sure I'm reporting a bug, its more of a feature request. In the case that I run all of my tests, i.e. I don't filter them in any way, the resulting XML `<testsuite>` tag will always have the same name attribute value.It has only just occured to me that the name may change if I apply soe sort of test filtering, however this is not something I want to do.

**Comment by jfemia** [comment] 2016-12-06 13:41
Duplicate of #469?

**Comment by horenmar** [comment] 2017-01-26 15:55
The `name` attribute of `testsuite` tag currently defaults to the binary name and can be override by using the `-n` cli flag.

**Closed by horenmar** 2017-01-26 15:55 UTC
